### ISSUE TITLE
Question: combine Opy with Transcrypt?

### ISSUE THREAD

**Issue by pjbonestroo** [QQuick/Opy#18]
Hi,
I have multiple python modules which make a single page Javascript application by compilation using Transcrypt. Now I would like to obfuscate my code for commercial reasons. Is it possible to use Opy for this?
So preferred steps:
1. Obfuscate using Opy
2. Compile obfuscated code using Transcrypt

Is this possible?
(I didn't try it yet, but I will, and I guess it is good to have the question posted to help others)

Regards,
Pieter Jan

**Comment by JdeH** [comment]
Hi Pieter Jan

I've never tried, since for me minification was obfuscation enough.
But I think your proposed approach will work fine.
However consider switching off string obfuscation, since that may generate strings that cannot be digested by some browsers.

Kind regards
Jacques

**Comment by pjbonestroo** [comment]
After a few hours of testing, I gave up. I still think it is possible, but maybe it is just easier to use an Javascript obfuscator, since I use a lot of javascript functions inside my python files.
Best regards,
Pieter Jan

**Comment by JdeH** [comment]
Since you gave up after a few hours, it must have been quite hard.
I'm curious what was the hard part.
Was it getting the Opy config file right?
And specifically that you had to explicitly exempt all the names of the native JS functions from obfuscation?

**Comment by pjbonestroo** [comment]
Yes, it was exactly that. I added a lot of JS functions to the Opy config file. But the last problem before I gave up was not very clear to me. In my javascript file, some array didn't have the length property, but I didn't know why. I can't reproduce because I already deleted it.

With this information, maybe it is interesting to make obfuscation a part of Transcrypt, to have optionally obfuscation available in Transcrypt. Since Transcrypt has the syntax tree and already handles the native javascript functions correctly, it should be easier to obfuscate correctly.

**Comment by JdeH** [comment]
Opy isn't specifically meant for Transcrypt, it was just for Python projects I was doing.
And it has to deal with multiple Python versions.
Transcrypt can indeed use the syntax tree, so it would be simpler in that sense.
However care has to be taken with native JS names, which complicate matters.
Since minification also supplies a fair level of obfuscation, taking also in_line JS into account,
I tend not consider adding obfuscation to TS having low priority.

**Comment by pjbonestroo** [comment]
I agree, it should have low priority. But on the long term it might be good to have it included in Transcrypt. I'm not sure if deep javascript obfuscation is possible if the code is generated by Transcrypt. So for deep obfuscation it might be needed to have obfuscation in both Transcrypt and javascript, sequential.

**Comment by JdeH** [comment]
I would expect that obfuscating from the Python source tree would be quite "deep", unless there's much native JS included in pragma's or used from external libs.
