### ISSUE TITLE
obfuscationCharacters not defined

### ISSUE THREAD

**Issue by guillermoares** [QQuick/Opy#19]
The last version in master branch does not define this variable (but it does use it).

**Comment by JdeH** [comment]
Thanks, will look into this!

**Comment by JdeH** [comment]
Thanks!

Indeed the latest commit is expermental, and as you found out, has serious errors.
I've crafted a 1st release to be used instead.

Kind regards
Jacques

**Comment by kkihara** [comment]
I have similar issues. I downloaded the source code from the "release" tab, 169ed4e. There are some syntax errors in that version line 423 and 538. Is that the correct 1st release to download?

**Comment by JdeH** [comment]
Thanks, that's bad...
There shouldn't be such errors in a release.
I'll look into it.

**Comment by JdeH** [comment]
The Phaistos prerelease should solve this.
Let me know if there are still problems.

KR
Jacques
