### ISSUE TITLE
Instructions of use are not clear

### ISSUE THREAD

**Issue by jimmycorkhill** [QQuick/Opy#20]
I'm sorry but I can't understand how I'm supposed to use your obfuscator.

I had opy.py and the config in a directory with a script I want to obfuscate. 

What now? You said "run opy.py" but that doesn't work and I can't see a specification of which .py file it is meant to target etc. 

Thanks

**Comment by JdeH** [comment]
If  you run `python opy.py` in the directory of your script, it will obfuscate all python files it find. If your project dir is called `myproject` the results will be in a sibling dir 'myproject_opy'. Let me know if this helps enough.
