### ISSUE TITLE
keyword parameters MySQLdb.connect(external module) need to be kept intact

### ISSUE THREAD

**Issue by nyim** [QQuick/Opy#21]
while in my code:
MySQLdb.connect( p1=xx, p2=xx)
and I added MySQLdb to external_modules

expected:
the p1 and p2 should be kept as original names.

actual:

> python3 ../py_opy/x.py 
> Traceback (most recent call last):
>   File "../py_opy/x.py", line 26, in <module>
>     , l1ll_opy_ = l1_opy_ (u"ࠪࡸࡪࡹࡴࠨࠆ")
>   File "/usr/lib64/python3.4/site-packages/MySQLdb/__init__.py", line 86, in Connect
>     return Connection(*args, **kwargs)
>   File "/usr/lib64/python3.4/site-packages/MySQLdb/connections.py", line 204, in __init__
>     super(Connection, self).__init__(*args, **kwargs2)
> TypeError: 'l1l1l_opy_' is an invalid keyword argument for this function

[opy_config.txt](https://github.com/QQuick/Opy/files/1263528/opy_config.txt)

the codes as below:
```python
import MySQLdb
if __name__ == '__main__':
    MySQLdb.connect( host = '127.0.0.1'
            , port = 3306
            , user = 'test'
            , passwd = 'test'
            , db = 'test'
            , charset = 'utf8'
            , use_unicode = True                                
            , sql_mode = 'test'
            )
```

**Comment by JdeH** [comment]
Hi,

To keep keyword params as is, Opy performs a recursive search in all external modules.
However, this only works for explicit, so known, keywords.

So in the construction:
`return Connection(*args, **kwargs)`
Opy isn't able to find out which keywords to spare.

Note that Opy doesn't perform a full parse, but only a scan.
It spares certain words, regardless of their context.
So it cannot syntactically determine that e.g. `port` is a keyword, rather than some other kind of name.

The workaround here is to include port, user, passwd, db, charset, use_unicode and sql_mode in the `plain_names` section of opy_config.txt.

Kind regards
Jacques

**Comment by nyim** [comment]
Thank you.
What a quick response.

I found another way to work around by adding MySQLdb.connections to
external modules.

**Comment by JdeH** [comment]
Great!
That's probably the best way.

**Comment by shaneberry** [comment]
I am having the same issue, so I tried using your suggestion of passing a dict in as the arguments to the external module's method, but it mangles the key names in the dict now.  How do I keep it from doing that?

**Comment by BuvinJT** [comment]
I believe you could a) disable string obfuscation entirely by setting `obfuscate_strings=false` (which is less than ideal) or b) call the `unScramble()` function on those keys (which is a function that is injected by opy) to reverse those string obfuscations.  Of course, it doing that would break it when running in clear text...

If you post an example of your code this might be a bit easier to solve directly.  I maybe able to revise my fork of Opy to make the solution cleaner for you.  I've already added a collection of new features...

**Comment by BuvinJT** [comment]
You could also use the `plain_files` + `external_modules` options to isolate a separate module for defining constants you don't want to obfuscate.  Depending on the context, I can think of many ways for handling this...  Although some of my ideas are proprietary secrets I use, so I'll have to tread carefully...

**Comment by shaneberry** [comment]
I created a dictionary in a plain_file and passed it in the function like this my_function(**my_dictionary) to resolve the arguments.

Thanks for the help!
