### ISSUE TITLE
opy obfuscated only itself but didn't obfuscate the .py

### ISSUE THREAD

**Issue by NewUserHa** [QQuick/Opy#26]
```
\folder
   code.py
   opy.py
   opy_config.txt
```
```
\folder
  \folder2
     code.py
      opy.py
      opy_config.txt
```

both folder structures failed.
py3.5, win10 10586

In the folder_opy folder, the opy.py is obfuscated, but the code.py is the same as the original one

**Comment by JdeH** [comment]
What's the encoding of your code.py?

**Comment by NewUserHa** [comment]
I tried gbk, it says ''gbk' codec can't decode byte...'
I tried utf8, it is this situation.

**Comment by JdeH** [comment]
Can you mail me a small example of Python code that Opy can't handle?
It's important that the example is complete (runnable) but it's ok if it's a very small test program.
Please mail it to: info@transcrypt.org.

**Comment by NewUserHa** [comment]
The reason is the file name is 'code.PY'

**Comment by JdeH** [comment]
OK, will fix this, thanks!

**Comment by JdeH** [comment]
I've seen it's just the config file.
Please change accordingly:
```

#====================================================================================================
# Extensions of files that should be obfuscated
# Typically these are files containing Python source code
# Other files are just copied to the target directory
#====================================================================================================

source_extensions = '''
py
PY
pyx
PYX
'''

```

I've adapted the default config file, but will wait with commit to accumulate some more fixes.

KR
Jacques
